---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: ozidochub/app:latest
          ports:
            - containerPort: 5000
          env:
            - name: db_root_password
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5000
    nodePort: 32222
  selector:
    app: flaskapi
  type: NodePortß