apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: deneme
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      - name: db
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d/init.sql
      volumes:
      - name: init-sql
        hostPath:
          path: /db/init.sql
      - name: data
        hostPath:
          path: /data

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 32000
    targetPort: 3306
